####################################################
# Set prefix
####################################################
unbind `
set-option -g prefix `
bind-key ` send-prefix

# base index
set -g base-index 1
set -g pane-base-index 1

# true colors
set -g default-terminal "${TERM}"
set -g terminal-overrides ",*:RGB"

# status bar
set-option -g status-position top
set -g status-style bg=default,fg=black,bright
set -g status-left ""
set -g status-right "#[fg=black,bright]#S"

# windows
set -g window-status-format " #I "
set -g window-status-current-format " #I "

set -g window-status-bell-style "bg=red,nobold"
set -g window-status-current-style "#{?window_zoomed_flag,bg=gray,bg=yellow,nobold}"

# pane lines
set -g pane-border-lines simple
set -g pane-border-style fg=black,bright
set -g pane-active-border-style fg=yellow

# split panes using \ and -
# bind | split-window -h
bind '\' split-window -h
bind - split-window -v

#####################################################
# Reload config
#####################################################
bind r source-file ~/.tmux.conf

# Especifica que el terminal por defecto dentro de tmux es un tipo moderno
set -as terminal-features "xterm-256color:RGB"

#####################################################
# Vim style pane selection using Alt-vim without prefix
#####################################################

bind -n M-left select-pane -L
bind -n M-right select-pane -R
bind -n M-up select-pane -U
bind -n M-down select-pane -D

# Switch windows using Alt-a and Alt-p without prefix
bind -n M-n next-window
bind -n M-p previous-window

#####################################################
# Copy mode bindings for vi
#####################################################

# set vi-mode
set-window-option -g mode-keys vi

# keybindings copy-mode
bind-key v copy-mode
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection

#####################################################
# set options
#####################################################
set -g renumber-windows on

set -g escape-time 0
set -g mouse on
set -g repeat-time 1000

# don't rename windows automatically
set-option -g allow-rename off

# Use vim in navigation and seleccion
set-option -g mode-keys vi
set-option -g history-limit 10000

#####################################################
# List of plugins
#####################################################
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Other plugins:
set -g @plugin 'tmux-plugins/tmux-yank'  

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
