####################################################
# Set prefix
####################################################
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# split panes using | and -
# bind | split-window -h
# bind - split-window -v

# alt h and alt v to split
bind -n M-v split-window -h
bind -n M-s split-window -v

unbind '"'
unbind %

#####################################################
# Reload config
#####################################################
bind r source-file ~/.tmux.conf

# Especifica que el terminal por defecto dentro de tmux es un tipo moderno
set -as terminal-features "xterm-256color:RGB"

#####################################################
# Vim style pane selection using Alt-vim without prefix
#####################################################
# bind -n M-h select-pane -L
# bind -n M-l select-pane -R
# bind -n M-k select-pane -U
# bind -n M-j select-pane -D

bind -n M-left select-pane -L
bind -n M-right select-pane -R
bind -n M-up select-pane -U
bind -n M-down select-pane -D

# Switch windows using Alt-a and Alt-p without prefix
bind -n M-n next-window
bind -n M-p previous-window

bind -n M-0 select-window -t 0
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9

# Open window seleccion with Alt-w
# bind -n M-w choose-tree

#####################################################
# Copy mode bindings for vi
#####################################################

# set vi-mode
set-window-option -g mode-keys vi

# keybindings copy-mode
bind-key v copy-mode
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection

#####################################################
# set options
#####################################################
set -g mouse on
set -g repeat-time 1000
set-option -g status-position top

# don't rename windows automatically
set-option -g allow-rename off

# Use vim in navigation and seleccion
set-option -g mode-keys vi
set-option -g history-limit 10000

# DESIGN TWEAKS

# don't do anything when a 'bell' rings
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

#####################################################
# TokyoNight colors for Tmux
#####################################################
set -g @catppuccin_window_status_style "rounded"

set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
# set -agF status-right "#{E:@catppuccin_status_cpu}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"
# set -agF status-right "#{E:@catppuccin_status_battery}"

#####################################################
# List of plugins
#####################################################
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Other plugins:
# set -g @plugin 'jimeh/tmuxifier'
set -g @plugin 'omerxx/tmux-floax'
set -g @plugin 'omerxx/tmux-sessionx'
set -g @plugin 'tmux-plugins/tmux-yank'  
set -g @plugin 'catppuccin/tmux#v2.1.3' 

# sessionx config
set -g @sessionx-bind M-o
set -g @sessionx-prefix off
set -g @sessionx-fzf-builtin-tmux 'off'
set -g @sessionx-window-mode 'on'

# tmux-float config
set -g @floax-bind '-n M-f'

# Load catppuccin
run ~/.tmux/plugins/tmux/catppuccin.tmux
# run ~/.config/tmux/plugins/tmux-plugins/tmux-cpu/cpu.tmux

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
